### ISSUE TITLE
App not working, throwing error

### ISSUE THREAD

**Issue by tejaswi755** [arpitv970/news-app#1]
## Error: TypeError: Cannot read properties of undefined (reading 'length')
![Screenshot 2022-05-18 at 2 08 57 PM](https://user-images.githubusercontent.com/75516011/168996666-bc667a38-59c2-461c-a74f-6223e556f7d9.png)

**Comment by lakshay-7014** [comment]
This issue is raised because @arpitv970  didn't push the API key in main code base (which is actually a good practice for security purpose).
As `.env.local` is ignored by git , which is usually used to store API key .
![53d7cb9c-5eb2-4f35-a08c-32a5a1289b3f](https://user-images.githubusercontent.com/73326673/169359999-0c5426a3-2bc8-4b42-8bb2-d6366fcfbbbf.jpg)

**Comment by arpitv970** [comment]
Yeah, that's correct @lakshay-7014 news limited API requests per day for free, so I did that to protect it from over-using the key.
